Refactoring, Dependency Management, and Enhanced Logging Features (#42) (#43)
* Update session data handling in exception

* Update incident view and exception handler

* Remove checkMissingIterableValueType config

* Update session handling in README

* Update workflows and standardize PHP version

* Update package discovery script path

* Update composer action in PHPStan workflow

* Update PHP CS Fixer and add IncidentFactory

* Remove unnecessary permissions from workflow

* Update Larastan package and path

* Optimize composer require in CI

* Update composer install commands in CI

* Improve CI error handling

* Update CI to conditionally install deps

* Update shell syntax in CI workflow

* Update OS check in test workflow

* Optimize composer require with --no-update

* Add "negoziator" to composer keywords

* Update CI triggers and README info

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -45,9 +45,16 @@ jobs:
 
       - name: Install dependencies
         run: |
-          composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}"
-          composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev
-          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
+          if ($env:RUNNER_OS -eq 'Linux') {
+            composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" --no-update || { echo 'Installing Laravel framework failed' ; exit 1; }
+            composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev --no-update || { echo 'Installing Orchestra Testbench failed' ; exit 1; }
+            composer update --${{ matrix.stability }} --prefer-dist --no-interaction || { echo 'Composer update failed' ; exit 1; }
+          } elseif ($env:RUNNER_OS -eq 'Windows') {
+            composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" --no-update || exit 1
+            composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev --no-update || exit 1
+            composer update --${{ matrix.stability }} --prefer-dist --no-interaction || exit 1
+          }
+        shell: pwsh
 
       - name: Execute tests
         run: vendor/bin/pest
