Update CI to conditionally install deps

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -42,9 +42,16 @@ jobs:
 
       - name: Install dependencies
         run: |
-          composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" || { echo 'Installing Laravel framework failed' ; exit 1; }
-          composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev || { echo 'Installing Orchestra Testbench failed' ; exit 1; }
-          composer update --${{ matrix.stability }} --prefer-dist --no-interaction || { echo 'Composer update failed' ; exit 1; }
+          if [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
+            set -e
+            composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" || { echo 'Installing Laravel framework failed' ; exit 1; }
+            composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev || { echo 'Installing Orchestra Testbench failed' ; exit 1; }
+            composer update --${{ matrix.stability }} --prefer-dist --no-interaction || { echo 'Composer update failed' ; exit 1; }
+          else
+            composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" || exit 1
+            composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev || exit 1
+            composer update --${{ matrix.stability }} --prefer-dist --no-interaction || exit 1
+          fi
 
       - name: Execute tests
         run: vendor/bin/pest
