Improve CI error handling

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -42,10 +42,9 @@ jobs:
 
       - name: Install dependencies
         run: |
-          set -e
-          composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}"
-          composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev
-          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
+          composer require "laravel/framework:${{ matrix.php-laravel-testbench.laravel }}" || { echo 'Installing Laravel framework failed' ; exit 1; }
+          composer require "orchestra/testbench:${{ matrix.php-laravel-testbench.testbench }}" --dev || { echo 'Installing Orchestra Testbench failed' ; exit 1; }
+          composer update --${{ matrix.stability }} --prefer-dist --no-interaction || { echo 'Composer update failed' ; exit 1; }
 
       - name: Execute tests
         run: vendor/bin/pest
